CREATE TABLE IF NOT EXISTS users (
    id UUID DEFAULT uuid_generate_v4 () PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    email TEXT NOT NULL UNIQUE,
    PASSWORD TEXT NOT NULL,
    created_by TEXT NOT NULL,
    created_on TEXT NOT NULL,
    ROLE TEXT NOT NULL
)